# Generated by Django 4.0.5 on 2022-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название слайда')),
                ('text', models.CharField(max_length=260, verbose_name='Текст слайда')),
                ('image', models.ImageField(upload_to='swipers/', verbose_name='Картинка сайда')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания слайда')),
                ('available', models.BooleanField(default=True, verbose_name='Отображение слайда')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='Порядок отображения слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('display_order',),
            },
        ),
        migrations.AddConstraint(
            model_name='swiper',
            constraint=models.UniqueConstraint(fields=('title',), name='unique swiper value'),
        ),
    ]
