# Generated by Django 4.0.5 on 2022-09-16 07:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования заказа')),
                ('status', models.CharField(choices=[('order_is_completed', 'заказ выполнен'), ('order_in_progress', 'заказ на этапе выполнения'), ('order_in_progress', 'заказ на этапе выполнения'), ('order_asks_details', 'заказ требует уточнений'), ('new_order', 'новый заказ'), ('order_cancelled', 'заказ отменён')], default='new_order', max_length=50, verbose_name='Статус заказа')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Населенный пункт')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица, дом, квартира')),
            ],
        ),
    ]
