# Generated by Django 4.0.5 on 2022-09-19 13:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования заказа')),
                ('status', models.CharField(choices=[('order_is_completed', 'заказ выполнен'), ('order_in_progress', 'заказ на этапе выполнения'), ('order_in_progress', 'заказ на этапе выполнения'), ('order_asks_details', 'заказ требует уточнений'), ('new_order', 'новый заказ'), ('order_cancelled', 'заказ отменён')], default='new_order', max_length=50, verbose_name='Статус заказа')),
                ('delivery', models.CharField(choices=[('SDEK', 'СДЭК'), ('Yandex', 'Яндекс'), ('Russian_post', 'Почта России')], default='SDEK', max_length=50, verbose_name='Доставка')),
                ('payment', models.CharField(choices=[('by_fact', 'при получении'), ('online', 'онлайн'), ('cashless', 'безналичный расчет')], default='by_fact', max_length=50, verbose_name='Оплата')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Населенный пункт')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица, дом, квартира')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('cur_price', models.PositiveIntegerField(verbose_name='Цена со скидкой')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.element', verbose_name='Деталь')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
