# Generated by Django 4.0.5 on 2022-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ('company',), 'verbose_name': 'Компания', 'verbose_name_plural': 'Логистические компании'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
