# Generated by Django 4.0.5 on 2022-10-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_element_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
