# Generated by Django 4.0.5 on 2022-08-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название детали')),
                ('measurement_unit', models.CharField(max_length=30, verbose_name='Ед. измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Кол-во в наличии')),
                ('article', models.CharField(db_index=True, max_length=50, verbose_name='Артикул')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Модель/Группа')),
            ],
            options={
                'verbose_name': 'Модель/Группа',
                'verbose_name_plural': 'Модели/Группы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Вrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Бренд')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ElementHasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.element', verbose_name='Деталь')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group', verbose_name='Модель/Группа')),
            ],
            options={
                'verbose_name': 'Принадлежность к группе',
                'verbose_name_plural': 'Принадлежность к группам',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='catalog.вrand', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='element',
            name='groups',
            field=models.ManyToManyField(related_name='groups', through='catalog.ElementHasGroup', to='catalog.group', verbose_name='Модели/Группы'),
        ),
        migrations.AddConstraint(
            model_name='elementhasgroup',
            constraint=models.UniqueConstraint(fields=('element', 'group'), name='unique elements in group value'),
        ),
    ]
