# Generated by Django 4.0.5 on 2022-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('title', 'article'), name='unique element value'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('title',), name='unique group value'),
        ),
        migrations.AddConstraint(
            model_name='вrand',
            constraint=models.UniqueConstraint(fields=('title',), name='unique brand value'),
        ),
    ]
