# Generated by Django 4.0.5 on 2022-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_element_unique element value_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='unique group value',
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Модель/Группа'),
        ),
    ]
