# Generated by Django 4.0.5 on 2022-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_group_unique group value_alter_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Модель/Группа'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('title',), name='unique group value'),
        ),
    ]
