# Generated by Django 4.0.5 on 2022-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productphoto_elementhasproductphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='image',
        ),
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ManyToManyField(related_name='photos', through='catalog.ElementHasProductPhoto', to='catalog.productphoto', verbose_name='Фото'),
        ),
    ]
