# Generated by Django 4.0.5 on 2022-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_element_image_element_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='element',
            name='measurement_unit',
            field=models.CharField(default='шт.', max_length=30, verbose_name='Ед. измерения'),
        ),
    ]
