# Generated by Django 4.0.5 on 2022-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_image_element_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementhasproductphoto',
            options={'verbose_name': 'Снимок детали', 'verbose_name_plural': 'Снимки деталей'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ('display_order',), 'verbose_name': 'Фото продукции', 'verbose_name_plural': 'Фото продукции'},
        ),
        migrations.AddField(
            model_name='productphoto',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок расположения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность на сайте'),
        ),
    ]
