# Generated by Django 4.0.5 on 2022-08-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_elementhasproductphoto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementhasproductphoto',
            old_name='image',
            new_name='photo',
        ),
    ]
