# Generated by Django 4.0.5 on 2022-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_elementhasgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='available',
            field=models.BooleanField(default=True, null=True, verbose_name='Отображение на сайте'),
        ),
    ]
