# Generated by Django 4.0.5 on 2022-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_element_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='available',
            field=models.BooleanField(verbose_name='Отображение на сайте'),
        ),
    ]
