name: Kotlovoy62


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  deploy:
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        # passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd kotlovoy
          git pull
          cd infra
          docker-compose down
          docker-compose up -d --build
